name: Build BigTreeTech CB1 OS image
on: workflow_dispatch
jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ccache debian-archive-keyring debootstrap device-tree-compiler dwarves gcc-arm-linux-gnueabihf jq libbison-dev libc6-dev-armhf-cross sudo apt-get install libelf-dev libfl-dev liblz4-tool libpython2.7-dev libusb-1.0-0-dev sudo apt-get install pigz pixz pv swig pkg-config python3-distutils qemu-user-static u-boot-tools sudo apt-get install distcc uuid-dev lib32ncurses-dev lib32stdc++6 apt-cacher-ng sudo apt-get install aptly aria2 libfdt-dev libssl-dev
      - name: Checkout bigtreetech/CB1-Kernel
        run: |
          git clone 'https://github.com/bigtreetech/CB1-Kernel.git'
      - name: Build OS image
        run: |
          cd CB1-Kernel
          sudo ./build.sh
