name: Build BigTreeTech CB1 OS image
on: workflow_dispatch
jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ccache debian-archive-keyring debootstrap device-tree-compiler dwarves gcc-arm-linux-gnueabihf jq libbison-dev libc6-dev-armhf-cross libelf-dev libfl-dev liblz4-tool libpython2.7-dev libusb-1.0-0-dev pigz pixz pv swig pkg-config python3-distutils qemu-user-static u-boot-tools distcc uuid-dev lib32ncurses-dev lib32stdc++6 apt-cacher-ng aptly aria2 libfdt-dev libssl-dev
      - name: Checkout bigtreetech/CB1-Kernel
        run: |
          git clone 'https://github.com/bigtreetech/CB1-Kernel.git'
      - name: Build OS image
        run: |          
          cd CB1-Kernel
          echo 'BUILD_OPT="image"' >> userpatches/config-build.conf
          sudo ./build.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CB1 Images
          path: ~/CB1-Kernel/output/images/**/*
          overwrite: true
      - name: Release artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ~/CB1-Kernel/output/images/**/*